### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by GlitchyReal** [316austin316/Silent-Hill-3-Modding#1]
I've downloaded the latest release, but I don't know how to launch the .py files.
It's probably something super basic that I just don't get lol

**Comment by 316austin316** [comment]
well, you open gui.py, it asks you to select the .arc file and then it exports textures. reimport button basically does the opposite, let me know if you need any more clarification, if not, i'll close the issue in a few days.

**Comment by 316austin316** [comment]
No reply so I'll close it up.
